# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be73878f0a87bc852be6e0288f48047964bf27892caa7fee446ec802029311f68aea41846dad08fcd11b995fe11e3938c18920b9bdef4b633adff54843bc1743

test:
  secret_key_base: c964e0493984e20cacf782e2e1d26757f5198d4d671da62adf7216c616ff558732b33b8840d1ae87a695fde0caa98e1631a2eba81961d83aedbc5da5cd3ffdb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
